# Generated by Django 2.0.8 on 2018-09-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20180912_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
